services:
  - type: web
    name: vegito-bot
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    plan: free
    region: oregon
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
